### ISSUE TITLE
topguw should to adapt with USRP

### ISSUE THREAD

**Issue by stackprogramer** [bastienjalbert/topguw#9]
Hi,Bastien RTL-SDR and HackRFOne is not good for cracking gsm because they had 8-bit ADC and large frequency correction error ppm, so they have  random jitter  ..........they don't have good selectivity...
see these links
https://blog.stackprogramer.xyz/en/2017/08/20/selectivity-and-sensitivity-in-sdr-hardwares/

https://blog.stackprogramer.xyz/en/2017/07/06/observing-random-jitter-in-hackrf-one-in-high-bandwidth-with-high-carrier-modulation/

for high quality So for GSM topguw should adapt with USRP.
thanks for attention.

**Comment by bastienjalbert** [comment]
The RTL-SDR part is because it is a affordable tool. The main goal of Topguw is to try to find Kc key from recorded files, and these files could be sniffed by SDR, USRP, ... what you want. You can use Topguw "offline" so the tool doesn't really matter. 

By the way almost all telephone companies had implemented solutions that make Topguw and Karsten Nohl exploit outdated..
